[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Gnosis Research Center wiki"
authors = [{name = "Jaime Cernuda", email = "none"}]
dynamic = ["version", "description"]
